### ISSUE TITLE
Support for Collections

### ISSUE THREAD

**Issue by AJ-Acevedo** [mathaywarduk/jekyll-search#2]
Your plugin looks very clean and was simple to install. Would be great to add it to the [JekyllKB](https://github.com/AJAlabs/jekyllkb) project.

Any chance you'll be adding support for [Jekyll 2.1.0 Collections](http://jekyllrb.com/docs/collections/)?

**Comment by iloveip** [comment]
Hello,
Does this plugin support Jekyll Collections now?

**Comment by mathaywarduk** [comment]
@iloveip Not yet, I've not really been keeping it up-to-date recently.
