### ISSUE TITLE
A couple of errors

### ISSUE THREAD

**Issue by andykirk** [mathaywarduk/jekyll-search#6]
Hi,

Just been looking through the code for this and I noticed 2 things:

1.
search.js line 117 is missing `item.seach_omit != "true" && `

2.
feed.json line 47, I'm pretty sure it should read:
`        "seach_omit": "{{ page.search_omit }}"`
instead of:
`        "seach_omit": "{{ post.search_omit }}"`
(page vs. post)

Thanks

Edit: oh, and re. 1 notice the typo 'seach' should be 'search' on this line and corrected everywhere in feed.json

**Comment by karlbateman** [comment]
Have proposed typo fix in #8 and not sure if this is the reason for me still seeing results despite the presence of search_omit: true in front matter.

**Comment by andykirk** [comment]
As far as I can remember, results weren't omitted for me either, see 1 above. Things work fine for me now with that change in place.

**Comment by mathaywarduk** [comment]
Fixed with #8
