### ISSUE TITLE
Liquid syntax error

### ISSUE THREAD

**Issue by iloveip** [mathaywarduk/jekyll-search#9]
Hello,

I'm trying to use this plugin, but I get a Liquid syntax error when I build the site:
````
Error: Liquid syntax error: Expected id but found open_square in "item in site.[item.label]"
````

Is there any way to fix it?

**Comment by krcabrer** [comment]
I have the same problem.

Any suggestion?

**Comment by svetlanapuro** [comment]
@krcabrer Check out AlgoliaSearch for Jekyll https://github.com/algolia/algoliasearch-jekyll. It's easy to set up and I ended up using it.
